#!/bin/bash

# Helper functions for maintaining daily notes

TODOSFILE="/Users/katie.fenn/Documents/Work-notes/work-todos.md"

function todos {
  if [[ $1 == "show" || $1 == "s"  ]]; then
    grep -n "\[ \] TODO" $TODOSFILE | cut -f1 -f5- -d:
  elif [[ $1 == "new" || $1 == "n"  ]]; then
    {
      echo "**$(date +'%d/%m/%Y %H:%M')**: [ ] TODO: $2";
    } >> $TODOSFILE
  elif [[ $1 == "complete" || $1 == "c"  ]]; then
    sed -i .bak "$2s/\[ \]/\[x\]/" $TODOSFILE
  fi
}
